name: Publish Packages

on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Set tag to version
        run: dotnet TagToVersion -t ${{ github.ref }}

      - name: Publish FluentEmail.Core
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/HangfireMediatorBridge.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
